/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  ChevronDown,
  Star,
  ShieldCheck,
  Zap,
  Users,
  MessageCircle,
  Calendar,
  CheckCircle,
  Clock,
  ExternalLink,
  ChevronRight,
  Stethoscope
} from 'lucide-react';
import { Language, Specialty, Review } from '../types';
import { DynamicIcon } from './DynamicIcon';
import { dbService } from '../lib/supabase';

interface LandingPageProps {
  language: Language;
  specialties: Array<Specialty & { doctor_count?: number }>;
  onSpecialtySelect: (specialtyId: string) => void;
  onOpenAuth: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({
  language,
  specialties,
  onSpecialtySelect,
  onOpenAuth,
}) => {
  const isRtl = language === 'ar';

  // State for FAQ accordions
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  const [reviews, setReviews] = useState<Review[]>([]);

  useEffect(() => {
    const loadReviews = async () => {
      try {
        const allReviews = await dbService.getAllReviewsPublic();
        setReviews(allReviews);
      } catch (error) {
        console.error('Failed to load public reviews', error);
      }
    };

    loadReviews();
  }, []);

  const t = {
    specTitle: isRtl ? 'تصفح العيادات حسب التخصص' : 'Browse Clinics by Specialty',
    specSubtitle: isRtl ? 'ابحث عن أفضل طبيب متخصص بناءً على احتياجك الصحي المحدد.' : 'Search the best certified specialist based on your specific health requirements.',
    whyTitle: isRtl ? 'لماذا تختار منصة طمني بلس؟' : 'Why Choose Tamenni Plus?',
    whySubtitle: isRtl ? 'نحن نقدم معايير لا تضاهى من الجودة والتحقق والسهولة.' : 'We provide unmatched standards of medical quality, checks, and patient comfort.',
    howTitle: isRtl ? 'كيف تعمل المنصة؟' : 'How It Works?',
    howSubtitle: isRtl ? 'احجز استشارتك في عيادة الطبيب بثلاث خطوات بسيطة ومباشرة.' : 'Book your clinical sessions in three simple, direct steps.',
    testiTitle: isRtl ? 'ماذا يقول المرضى عنا؟' : 'What Our Patients Say',
    testiSubtitle: isRtl ? 'آراء وتجارب حقيقية كتبها المرضى بكل مصداقية.' : 'Real verified stories written by happy patients about their clinical experiences.',
    faqTitle: isRtl ? 'الأسئلة الشائعة عن المنصة' : 'Frequently Asked Questions',
    faqSubtitle: isRtl ? 'هل لديك استفسار؟ اطلع على الأجوبة الشائعة.' : 'Have queries? Check out our compiled standard answers.',
  };

  const whyCards = [
    {
      icon: <ShieldCheck className="text-primary" size={24} />,
      title_ar: 'أطباء معتمدون وموثقون',
      title_en: '100% Verified Physicians',
      desc_ar: 'نقوم بمراجعة شهادات التخرج، الماجستير والدكتوراه، بالإضافة لكارنيه نقابة الأطباء قبل تفعيل أي حساب وتوفيره للجمهور.',
      desc_en: 'We manually review university degrees, certificates, and medical syndicate licenses before approving any doctor profile.'
    },
    {
      icon: <Zap className="text-primary" size={24} />,
      title_ar: 'حجز فوري مباشر',
      title_en: 'Instant Direct Booking',
      desc_ar: 'لا داعي للانتظار الطويل. اضغط على زر حجز العيادة لفتح دردشة مباشرة مع الطبيب أو سكرتارية العيادة عبر واتساب فورا.',
      desc_en: 'No wait times. Instantly initiate direct WhatsApp chat with the doctor or clinic reception with a single click.'
    },
    {
      icon: <Users className="text-primary" size={24} />,
      title_ar: 'خصوصية وأمان تام',
      title_en: 'Total Data Privacy',
      desc_ar: 'بياناتك وطلبات حجزك مؤمنة بالكامل وخاضعة لأعلى معايير الحماية لتستمتع برحلة علاج آمنة ومريحة.',
      desc_en: 'Your medical booking metadata remains safe, secure, and stored in line with high encryption protocols.'
    },
    {
      icon: <MessageCircle className="text-primary" size={24} />,
      title_ar: 'تقييمات حقيقية وصادقة',
      title_en: 'Authentic Patient Reviews',
      desc_ar: 'كل التقييمات المعروضة على الملفات هي لمرضى حقيقيين زاروا العيادة وتلقوا الرعاية المناسبة بالفعل.',
      desc_en: 'Every single feedback and rating is generated by real clinical visitors, providing absolute transparency.'
    }
  ];

  const howSteps = [
    {
      step: '01',
      title_ar: 'ابحث عن طبيبك',
      title_en: 'Find Your Doctor',
      desc_ar: 'اختر التخصص والمدينة أو اكتب اسم الطبيب وافرز حسب السعر أو التقييم.',
      desc_en: 'Filter by specialty, location, prices, or ratings to locate the most appropriate consultant.'
    },
    {
      step: '02',
      title_ar: 'تصفح الملف الطبي',
      title_en: 'Explore the Portfolio',
      desc_ar: 'شاهد صور العيادة، الأسعار، الشهادات العلمية، مواعيد العمل والتقييمات.',
      desc_en: 'Check real clinic photos, academic certificates, working days, fees, and patient opinions.'
    },
    {
      step: '03',
      title_ar: 'احجز عبر واتساب بلمسة',
      title_en: 'Book Instantly via WhatsApp',
      desc_ar: 'اضغط حجز ليفتح تطبيق واتساب برسالة جاهزة تفيد برغبتك بالحجز، وسيقوم فريق العمل بتأكيد موعدك.',
      desc_en: 'Press booking to open WhatsApp with an auto-filled greeting. The clinic will instantly lock in your slot.'
    }
  ];

  const faqs = [
    {
      q_ar: 'كيف تضمن المنصة مصداقية الأطباء وصحة شهاداتهم؟',
      q_en: 'How does the platform verify doctor credentials?',
      a_ar: 'يمر كل طبيب يسجل في المنصة بعملية تدقيق صارمة تتطلب تحميل شهاداته العلمية (بكالوريوس، ماجستير، دكتوراه)، وترخيص مزاولة المهنة، وكارنيه نقابة الأطباء الساري. يقوم فريقنا الإداري بمراجعة هذه الأوراق يدوياً والتحقق من رقم القيد بالنقابة قبل تفعيل الحساب.',
      a_en: 'Every registered physician undergoes a rigorous verification cycle requiring them to upload their degree certificates (B.Sc., M.Sc., Ph.D.), active medical syndicate cards, and clinical practice permits. Our administrative team manually audits these documents prior to profile activation.'
    },
    {
      q_ar: 'هل هناك أي رسوم إضافية تفرضها المنصة على حجز المريض؟',
      q_en: 'Are there any hidden fees or extra booking charges?',
      a_ar: 'خدمة البحث والحجز عبر منصة طمّني بلس مجانية ١٠٠% للمرضى. السعر الموضح في الملف التعريفي للطبيب هو السعر الفعلي للكشف الذي يتم دفعه داخل العيادة مباشرة دون أي زيادة.',
      a_en: 'Searching and booking clinical sessions on Tamny Plus is 100% free for all patients. The medical fee indicated on the doctor profile is the exact price you pay directly inside the clinic, with zero markups.'
    },
    {
      q_ar: 'ما الذي يحدث عند الضغط على زر "حجز موعد داخل العيادة"؟',
      q_en: 'What happens when I click the "Book Clinic Session" button?',
      a_ar: 'عند الضغط على الزر، ستقوم المنصة تلقائياً بفتح تطبيق واتساب على هاتفك أو جهازك ومراسلة رقم العيادة المخصص، مع كتابة رسالة ترحيبية جاهزة مثل (السلام عليكم دكتور، أرغب في حجز موعد داخل العيادة). يتيح لك ذلك تنسيق الموعد وتأكيده مع سكرتارية العيادة مباشرة وبكل مرونة.',
      a_en: 'When you tap the button, the platform automatically opens WhatsApp on your phone or web app and directs you to the clinic’s designated chat line, pre-filling a polite template (e.g. "Peace be upon you Dr., I would like to book a session..."). This allows flexible coordinate confirmation with the receptionist.'
    },
    {
      q_ar: 'أنا طبيب، كيف يمكنني الانضمام لمنصة طمّني بلس وتفعيل حسابي؟',
      q_en: 'I am a physician, how can I join and list my clinic?',
      a_ar: 'يمكنك ببساطة الضغط على زر "انضم كطبيب" في القائمة العلوية، وملء بيانات الحساب (اسم المستخدم، البريد، كلمة السر) ثم إكمال ملفك الشخصي التفصيلي ورفع أوراقك الثبوتية. بمجرد قيام الإدارة بالتحقق والقبول، سيظهر ملفك فوراً للمرضى لتبدأ في استقبال الزيارات الحقيقية ومتابعة تحليلاتك الرائعة.',
      a_en: 'Simply click "Join as Doctor" in the navbar, enter your core account credentials (username, email, password), and complete your comprehensive clinical profile including uploading your credentials. Once the administrator reviews and approves your submission, your profile will instantly go live.'
    }
  ];

  return (
    <div className="space-y-24 pb-12">
      
      {/* 1. SPECIALTIES SECTION */}
      <section id="specialties" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-16">
        <div className="text-center max-w-2xl mx-auto space-y-4">
          <h2 className="text-3xl font-black text-text-dark tracking-tight font-display">
            {t.specTitle}
          </h2>
          <p className="text-text-muted font-medium text-sm sm:text-base leading-relaxed">
            {t.specSubtitle}
          </p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 mt-12">
          {specialties.map((spec) => (
            <motion.div
              key={spec.id}
              whileHover={{ y: -6, scale: 1.02 }}
              onClick={() => onSpecialtySelect(spec.id)}
              className="p-6 bg-white rounded-2xl border border-border-brand shadow-soft cursor-pointer text-center space-y-4 hover:border-primary/20 transition-all duration-300 group"
            >
              <div className="w-12 h-12 rounded-xl bg-primary/5 text-primary flex items-center justify-center mx-auto group-hover:bg-primary group-hover:text-white transition-colors duration-300">
                <DynamicIcon name={spec.icon} size={22} />
              </div>
              <div>
                <h3 className="text-sm font-bold text-text-dark group-hover:text-primary transition-colors">
                  {isRtl ? spec.name_ar : spec.name_en}
                </h3>
                {(spec.doctor_count || 0) > 0 && (
                  <p className="text-[10px] text-text-muted font-semibold mt-1">
                    {spec.doctor_count} {isRtl ? 'أطباء معتمدين' : 'Certified Doctors'}
                  </p>
                )}
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* 2. WHY TAMNY PLUS SECTION */}
      <section id="about" className="bg-light-gray/40 py-20 border-y border-border-brand">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto space-y-4">
            <h2 className="text-3xl font-black text-text-dark tracking-tight font-display">
              {t.whyTitle}
            </h2>
            <p className="text-text-muted font-medium text-sm sm:text-base leading-relaxed">
              {t.whySubtitle}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-12">
            {whyCards.map((card, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
                className="p-8 bg-white rounded-3xl border border-border-brand shadow-soft space-y-4 hover:shadow-premium transition-all duration-300"
              >
                <div className="w-12 h-12 rounded-2xl bg-primary/5 flex items-center justify-center">
                  {card.icon}
                </div>
                <h3 className="text-base font-bold text-text-dark">
                  {isRtl ? card.title_ar : card.title_en}
                </h3>
                <p className="text-xs text-text-muted leading-relaxed font-medium">
                  {isRtl ? card.desc_ar : card.desc_en}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* 3. HOW IT WORKS */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto space-y-4">
          <h2 className="text-3xl font-black text-text-dark tracking-tight font-display">
            {t.howTitle}
          </h2>
          <p className="text-text-muted font-medium text-sm sm:text-base leading-relaxed">
            {t.howSubtitle}
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-16 relative">
          {howSteps.map((step, idx) => (
            <div key={idx} className="relative flex flex-col items-center text-center space-y-4 p-4 group">
              <span className="text-5xl font-black text-primary/10 tracking-wider font-display transition-transform duration-300 group-hover:scale-105">
                {step.step}
              </span>
              <h3 className="text-lg font-bold text-text-dark">
                {isRtl ? step.title_ar : step.title_en}
              </h3>
              <p className="text-xs text-text-muted font-medium leading-relaxed max-w-xs">
                {isRtl ? step.desc_ar : step.desc_en}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 4. VERIFIED TESTIMONIALS */}
      <section className="bg-light-gray/40 py-20 border-y border-border-brand">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto space-y-4">
            <h2 className="text-3xl font-black text-text-dark tracking-tight font-display">
              {t.testiTitle}
            </h2>
            <p className="text-text-muted font-medium text-sm sm:text-base leading-relaxed">
              {t.testiSubtitle}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
            {reviews.length === 0 ? (
              <div className="md:col-span-3 rounded-3xl border border-dashed border-border-brand bg-white p-8 text-center text-sm font-semibold text-text-muted">
                {isRtl ? 'لا توجد مراجعات معتمدة حالياً.' : 'No approved reviews are available yet.'}
              </div>
            ) : (
              reviews.slice(0, 3).map((review) => (
                <div
                  key={review.id}
                  className="p-8 bg-white rounded-3xl border border-border-brand shadow-soft flex flex-col justify-between space-y-6"
                >
                  <div className="flex items-center gap-1 text-amber-500">
                    {Array.from({ length: 5 }).map((_, idx) => (
                      <Star key={`${review.id}-${idx}`} size={14} fill={idx < review.rating ? 'currentColor' : 'none'} />
                    ))}
                  </div>
                  <p className="text-xs text-text-dark font-medium leading-relaxed italic">
                    &ldquo;{review.comment || review.review_text || ''}&rdquo;
                  </p>
                  <div className="flex items-center gap-3 border-t border-border-brand/60 pt-4">
                    <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center font-bold text-primary text-sm font-display">
                      {(review.patient_name || 'P').charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-text-dark">
                        {review.patient_name}
                      </h4>
                      <p className="text-[10px] text-text-muted mt-0.5 font-semibold">
                        {review.review_date ? new Date(review.review_date).toLocaleDateString(isRtl ? 'ar-EG' : 'en-US') : ''}
                      </p>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </section>

      {/* 5. FAQs SECTION */}
      <section id="faq" className="max-w-4xl mx-auto px-4 sm:px-6">
        <div className="text-center space-y-4 mb-12">
          <h2 className="text-3xl font-black text-text-dark tracking-tight font-display">
            {t.faqTitle}
          </h2>
          <p className="text-text-muted font-medium text-sm sm:text-base leading-relaxed">
            {t.faqSubtitle}
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, idx) => (
            <div
              key={idx}
              className="border border-border-brand rounded-2xl bg-white overflow-hidden transition-all duration-300"
            >
              <button
                onClick={() => setActiveFaq(activeFaq === idx ? null : idx)}
                className="w-full flex items-center justify-between p-6 text-right font-bold text-text-dark hover:bg-light-gray/20 transition-colors focus:outline-none"
              >
                <span className="text-sm sm:text-base text-right pr-2">
                  {isRtl ? faq.q_ar : faq.q_en}
                </span>
                <ChevronDown
                  size={18}
                  className={`text-text-muted transition-transform duration-300 ${
                    activeFaq === idx ? 'transform rotate-180' : ''
                  }`}
                />
              </button>

              <AnimatePresence initial={false}>
                {activeFaq === idx && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <div className="p-6 pt-0 text-xs sm:text-sm text-text-muted leading-relaxed font-medium border-t border-border-brand/40 bg-light-gray/10">
                      {isRtl ? faq.a_ar : faq.a_en}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </section>

    </div>
  );
};
export default LandingPage;
